# Generated by Django 3.1.4 on 2021-02-17 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('description', models.TextField(max_length=1000)),
                ('genre', models.CharField(choices=[('A', 'Action'), ('D', 'Drama'), ('C', 'Comedy'), ('H', 'History'), ('R', 'Romance')], max_length=1)),
                ('image', models.ImageField(upload_to='movie_images')),
                ('poster', models.ImageField(upload_to='movie_posters')),
                ('produced_date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TR', 'Top Rated'), ('RA', 'Recently Added'), ('MV', 'Most Viewed')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('trailer_link', models.URLField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_link', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_link', to='movies.movie')),
            ],
        ),
    ]
