# Generated by Django 3.1.4 on 2021-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviecast_actor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='actor_name',
            field=models.CharField(default='Unnamed Actor', max_length=50),
        ),
    ]
