# Generated by Django 3.1.4 on 2021-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210217_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='actor_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
