# Generated by Django 3.1.4 on 2021-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210217_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'A'), ('Drama', 'D'), ('Comedy', 'C'), ('History', 'H'), ('Romance', 'R')], max_length=10),
        ),
    ]
