# Generated by Django 3.1.4 on 2021-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210217_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('History', 'History'), ('Romance', 'Romance')], max_length=10),
        ),
    ]
