# Generated by Django 3.1.4 on 2021-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210217_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
    ]
