# Generated by Django 3.1.4 on 2021-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210221_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='actor_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
